##############################################################################
# For more information on parameters, refer to: 
# https://docs.gramaddict.org/#/configuration?id=configuration-file
#
# Note: be sure to comment out any parameters not used by adding a # in front
# AGAIN: YOU DON'T HAVE TO DELETE THE LINE, BUT ONLY COMMENT IT WITH A #!
##############################################################################
# General Configuration
##############################################################################

username: psy8s # you have to put your IG name here!
device: 128.14.109.187:21398 # GeeLark cloud device - authenticate first with ./geelark_glogin.sh
app-id: com.instagram.android
use-cloned-app: false
allow-untested-ig-version: false # Using an untested version of IG would cause unexpected behavior because some elements in the user interface may have been changed
screen-sleep: true
screen-record: false
speed-multiplier: 1
debug: false
close-apps: false
kill-atx-agent: false
restart-atx-agent: false
disable-block-detection: false
disable-filters: false
dont-type: false
# scrape-to-file: scraped.txt
total-crashes-limit: 5
count-app-crashes: false
shuffle-jobs: true
truncate-sources: 2-5

##############################################################################
# Actions - OPTIMIZED FOR MAXIMUM GROWTH
# Research-based strategy: Micro-influencers (10K-500K) with high engagement
##############################################################################

## PRIMARY STRATEGY: Hashtag-Based Growth (Highest Success Rate)
# Diverse audience sizes, 10-15% engagement rate, fast organic growth
hashtag-likers-recent: [ fitness, travel, foodie, photography, entrepreneur ]
hashtag-posts-recent: [ motivation, lifestyle, inspiration, health, mindset ]
hashtag-likers-top: [ fashion, art, fitness, foodporn, wanderlust ]
hashtag-posts-top: [ success, goals, wellness, adventure, positivity ]

## SECONDARY STRATEGY: Micro-Influencer Targeting
# 50K-300K followers, high engagement, relevant niches
blogger-followers: [ alexia_clark, whitneyysimmons, kayla_itsines, blogilates, cassey_ho ]
blogger-following: [ chloeting, pamela_rf, adriennelouise, nourishmovelove, popsugarfitness ]

## TERTIARY STRATEGY: Brand & Community Pages  
# 100K-500K followers, active communities, high engagement
blogger-post-likers: [ womensbest, gymshark, lululemon, myprotein, alo ]
blogger: [ humanfitproject, trainers, fitnessmotivation, healthyfood, mindbodygreen ]

## FEED STRATEGY: Organic Engagement
# Interact with your own feed for natural activity pattern
feed: 8-12

## OPTIONAL: Custom Lists (Create .txt files with targeted usernames)
# interact-from-file: [fitness_influencers.txt 10-15, local_accounts.txt 5-8]
# posts-from-file: viral_posts.txt

## Special modifier for jobs and sources
watch-video-time: 15-35
watch-photo-time: 3-4
# can-reinteract-after: 48 # the amount of hours that have to pass from the last interaction
delete-interacted-users: true

## Unfollow (unfollow jobs)
unfollow: 10-20
unfollow-any: 10-20
unfollow-non-followers: 10-20
unfollow-any-non-followers: 10-20
unfollow-any-followers: 10-20
unfollow-from-file: [usernames1.txt 7-15, usernames2.txt 6]

## Special modifier for unfollow jobs
sort-followers-newest-to-oldest: false
unfollow-delay: 15

## Remove followers (active jobs)
remove-followers-from-file: [remove1.txt 5-10, remove2.txt 6]

## Special modifier for remove followers
delete-removed-followers: true

## Post Processing
# analytics: false # no more supported
telegram-reports: false # for using telegram-reports you have also to configure telegram.yml in your account folder

## Special actions
# pre-script: pre_script_path_here
# post-script: post_script_path_here

##############################################################################
# Source Limits - OPTIMIZED FOR ENGAGEMENT & GROWTH
##############################################################################

interactions-count: 15-25        # Reduced for quality over quantity
likes-count: 2-4                 # More likes per user = better engagement signal
likes-percentage: 100            # Always like when interacting
stories-count: 1-3               # Watch stories for authentic behavior
stories-percentage: 50-70        # Increased story viewing
carousel-count: 2-4              # Browse carousels thoroughly
carousel-percentage: 80-100      # High carousel engagement
max-comments-pro-user: 1-2       # Thoughtful comments
comment-percentage: 20-30        # Strategic commenting (not too aggressive)
# pm-percentage: 10-20           # Direct messages (optional)
interact-percentage: 50-70       # Higher interaction rate for growth
follow-percentage: 50-70         # Strategic following (50-70% of interactions)
follow-limit: 30                 # Conservative follow limit per source
skipped-list-limit: 15-20        # More tolerance for skips
skipped-posts-limit: 8           # Higher post skip tolerance
fling-when-skipped: 1            # Fling once when reaching skip limit
min-following: 50                # Lowered from 100 for broader targeting

##############################################################################
# Total Limits Per Session - GROWTH OPTIMIZED
##############################################################################

total-likes-limit: 150-200       # Increased for more engagement
total-follows-limit: 60-80       # Balanced follow rate
total-unfollows-limit: 50-70     # Clean up old follows
total-watches-limit: 150-200     # High story engagement
total-successful-interactions-limit: 80-120  # Quality interactions
total-interactions-limit: 150-200  # Attempt more, achieve quality
total-comments-limit: 5-10       # Thoughtful commenting
total-pm-limit: 3-5              # Conservative DM strategy
total-scraped-limit: 100-150     # Data collection

##############################################################################
# Ending Session Conditions
##############################################################################

end-if-likes-limit-reached: true
end-if-follows-limit-reached: false
end-if-watches-limit-reached: false
end-if-comments-limit-reached: false
end-if-pm-limit-reached: false

##############################################################################
# Scheduling - OPTIMAL TIMING STRATEGY
##############################################################################

working-hours: [8.30-12.30, 14.00-18.00, 20.00-23.30]  # Peak engagement times (3 windows)
time-delta: 15-25                # Longer breaks between sessions (more human-like)
repeat: 180-240                  # 3-4 hour intervals between sessions
total-sessions: 3                # 3 quality sessions per day (manageable growth)
